name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        env:
          - { php: 8.1 }
          - { php: 8.2 }

    env: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.php }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install composer dependencies
        run: |
          composer install --no-progress

      - name: Lint PHP
        run: composer test:php:lint

      - name: Unit Tests
        run: composer test:php:unit
